<a href="https://colab.research.google.com/github/Harish14123/machine-learning-projects/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas usecase

1,ease of importing datasets

2.data cleaning

3.size mutability

4.reshaping and pivoting datasets

5.Efficient manuplation and extraction

6.stastistics analysis

In [ ]:
import pandas as pd
import numpy as np

#Data structures in panda

1.series-->>one dimensional

2.Dataframe-->> two dimensional

In [ ]:
#series
arr=pd.Series([1,2,3,4,5])
arr

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
arr[1]

np.int64(2)

In [ ]:
arr[2:5]

2    3
3    4
4    5
dtype: int64

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.values

array([1, 2, 3, 4, 5])

In [ ]:
arr.index

RangeIndex(start=0, stop=5, step=1)

# iloc-->>location based indexing

In [ ]:
arr.iloc[[2,3,0]]

2    3
3    4
0    1
dtype: int64

In [ ]:

arr.name='numbers'
indexs=['fruit1','fruit2','fruit3','fruit4','fruit5']
arr.index=indexs
arr

fruit1    1
fruit2    2
fruit3    3
fruit4    4
fruit5    5
Name: numbers, dtype: int64

In [ ]:
print(arr['fruit1'])

1

# loc-->>label based indexing

in loc indexing the end is also included

In [ ]:
arr.loc['fruit2']

np.int64(2)

In [ ]:
arr.loc['fruit1':'fruit4']

fruit1    1
fruit2    2
fruit3    3
fruit4    4
Name: numbers, dtype: int64

coditional selection

logical and

logical or

logical not

In [ ]:
arr>2

fruit1    False
fruit2    False
fruit3     True
fruit4     True
fruit5     True
Name: numbers, dtype: bool

In [ ]:
arr[arr>2]

fruit3    3
fruit4    4
fruit5    5
Name: numbers, dtype: int64

In [ ]:
#logical and
arr[(arr<5)& (arr>1)]

fruit2    2
fruit3    3
fruit4    4
Name: numbers, dtype: int64

In [ ]:
#logical or
arr[(arr<5)|(arr>1)]

fruit1    1
fruit2    2
fruit3    3
fruit4    4
fruit5    5
Name: numbers, dtype: int64

In [ ]:
#logical not
arr[~(arr>3)]

fruit1    1
fruit2    2
fruit3    3
Name: numbers, dtype: int64

# Dataframe

In [ ]:
data={
    'names':['mukesh','sai','rakesh','srinu','ramesh','venky'],
    'age':[22,21,25,20,np.nan,35],
    'department':['it','hr','finance','it','hr','hr'],
    'salaries':[30000,35000,40000,45000,50000,55000]
}

In [ ]:
data

{'names': ['mukesh', 'sai', 'rakesh', 'srinu', 'ramesh', 'venky'],
 'age': [22, 21, 25, 20, nan, 35],
 'department': ['it', 'hr', 'finance', 'it', 'hr', 'hr'],
 'salaries': [30000, 35000, 40000, 45000, 50000, 55000]}

In [ ]:
df=pd.DataFrame(data)
df

    names   age department  salaries
0  mukesh  22.0         it     30000
1     sai  21.0         hr     35000
2  rakesh  25.0    finance     40000
3   srinu  20.0         it     45000
4  ramesh   NaN         hr     50000
5   venky  35.0         hr     55000

In [ ]:
df.head(2)

    names   age department  salaries
0  mukesh  22.0         it     30000
1     sai  21.0         hr     35000

In [ ]:
df.tail(3)

    names   age department  salaries
3   srinu  20.0         it     45000
4  ramesh   NaN         hr     50000
5   venky  35.0         hr     55000

# Accessing rows and columns using iloc and loc

In [ ]:
df.iloc[1:3]

    names   age department  salaries
1     sai  21.0         hr     35000
2  rakesh  25.0    finance     40000

In [ ]:
df.iloc[0:3,0:3]

    names   age department
0  mukesh  22.0         it
1     sai  21.0         hr
2  rakesh  25.0    finance

In [ ]:
df.loc[1:3,['age','department']]

    age department
1  21.0         hr
2  25.0    finance
3  20.0         it

In [ ]:
df['age']

0    22.0
1    21.0
2    25.0
3    20.0
4     NaN
5    35.0
Name: age, dtype: float64

In [ ]:
df.drop('age',axis=1)

    names department  salaries
0  mukesh         it     30000
1     sai         hr     35000
2  rakesh    finance     40000
3   srinu         it     45000
4  ramesh         hr     50000
5   venky         hr     55000

In [ ]:
df

    names   age department  salaries
0  mukesh  22.0         it     30000
1     sai  21.0         hr     35000
2  rakesh  25.0    finance     40000
3   srinu  20.0         it     45000
4  ramesh   NaN         hr     50000
5   venky  35.0         hr     55000

In [ ]:
df.shape

(6, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   names       6 non-null      object
 1   age         5 non-null      float64
 2   department  6 non-null      object
 3   salaries    6 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

In [ ]:
df.describe()

             age      salaries
count   5.000000      6.000000
mean   24.600000  42500.000000
std     6.107373   9354.143467
min    20.000000  30000.000000
25%    21.000000  36250.000000
50%    22.000000  42500.000000
75%    25.000000  48750.000000
max    35.000000  55000.000000

In [ ]:
# Broadcasting
df['salaries']

0    30000
1    35000
2    40000
3    45000
4    50000
5    55000
Name: salaries, dtype: int64

In [ ]:
df['salaries']=df['salaries']+5000
df['salaries']

0    35000
1    40000
2    45000
3    50000
4    55000
5    60000
Name: salaries, dtype: int64

# Renaming the columns

In [ ]:
df.rename(columns={'department':'dept'},inplace=True)
df

    names   age     dept  salaries
0  mukesh  22.0       it     35000
1     sai  21.0       hr     40000
2  rakesh  25.0  finance     45000
3   srinu  20.0       it     50000
4  ramesh   NaN       hr     55000
5   venky  35.0       hr     60000

# unique values for a column

In [ ]:

print(df['dept'].unique())

['it' 'hr' 'finance']

In [ ]:
df['dept'].value_counts()

dept
hr         3
it         2
finance    1
Name: count, dtype: int64

In [ ]:
df['promoted_salary']=df['salaries']+10000
df

    names   age     dept  salaries  promoted_salary
0  mukesh  22.0       it     35000            45000
1     sai  21.0       hr     40000            50000
2  rakesh  25.0  finance     45000            55000
3   srinu  20.0       it     50000            60000
4  ramesh   NaN       hr     55000            65000
5   venky  35.0       hr     60000            70000

In [ ]:
df.isnull().sum()

names              0
age                1
dept               0
salaries           0
promoted_salary    0
dtype: int64

# Dealing with missing values

# 1. Droping null values

dropna()-->>removes row if it has a null value

dropna(how='any')-->>same as dropna()

dropna(how='all')-->>removes a row if it has all the values are null

dropna(axis=1)--->>>removes the column with null values

In [ ]:
df.dropna()

    names   age     dept  salaries  promoted_salary
0  mukesh  22.0       it     35000            45000
1     sai  21.0       hr     40000            50000
2  rakesh  25.0  finance     45000            55000
3   srinu  20.0       it     50000            60000
5   venky  35.0       hr     60000            70000

In [ ]:
df.dropna(how='any')

    names   age     dept  salaries  promoted_salary
0  mukesh  22.0       it     35000            45000
1     sai  21.0       hr     40000            50000
2  rakesh  25.0  finance     45000            55000
3   srinu  20.0       it     50000            60000
5   venky  35.0       hr     60000            70000

In [ ]:

df.dropna(how='all')

    names   age     dept  salaries  promoted_salary
0  mukesh  22.0       it     35000            45000
1     sai  21.0       hr     40000            50000
2  rakesh  25.0  finance     45000            55000
3   srinu  20.0       it     50000            60000
4  ramesh   NaN       hr     55000            65000
5   venky  35.0       hr     60000            70000

In [ ]:

df.dropna(axis=1)

    names     dept  salaries  promoted_salary
0  mukesh       it     35000            45000
1     sai       hr     40000            50000
2  rakesh  finance     45000            55000
3   srinu       it     50000            60000
4  ramesh       hr     55000            65000
5   venky       hr     60000            70000

#2. Filling missing values

1.using fillna() with mean(),median(),mode()

2.using forward fill and backward fill

In [ ]:
df['age']

0    22.0
1    21.0
2    25.0
3    20.0
4     NaN
5    35.0
Name: age, dtype: float64

In [ ]:
#mean()
df['age'].fillna(df['age'].mean())

0    22.0
1    21.0
2    25.0
3    20.0
4    24.6
5    35.0
Name: age, dtype: float64

In [ ]:
#median
df['age'].fillna(df['age'].median())

0    22.0
1    21.0
2    25.0
3    20.0
4    22.0
5    35.0
Name: age, dtype: float64

In [ ]:
#mode
df['age'].fillna(df['age'].mode())

0    22.0
1    21.0
2    25.0
3    20.0
4    35.0
5    35.0
Name: age, dtype: float64

In [ ]:
# drawback is if the first value null then null is filled in that
df['age'].fillna(method='ffill')

/tmp/ipykernel_4339/561162265.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['age'].fillna(method='ffill')

0    22.0
1    21.0
2    25.0
3    20.0
4    20.0
5    35.0
Name: age, dtype: float64

In [ ]:
#backword fill
# drawback is if the last value null then null is filled in that
df['age'].fillna(method='bfill')

/tmp/ipykernel_4339/3691216396.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['age'].fillna(method='bfill')

0    22.0
1    21.0
2    25.0
3    20.0
4    35.0
5    35.0
Name: age, dtype: float64

# Replacing a column value

In [ ]:
df['names'].replace('rakesh','sathish')

0     mukesh
1        sai
2    sathish
3      srinu
4     ramesh
5      venky
Name: names, dtype: object

In [ ]:
df['names']=df['names'].replace('rakesh','sathish')
df

     names   age     dept  salaries  promoted_salary
0   mukesh  22.0       it     35000            45000
1      sai  21.0       hr     40000            50000
2  sathish  25.0  finance     45000            55000
3    srinu  20.0       it     50000            60000
4   ramesh   NaN       hr     55000            65000
5    venky  35.0       hr     60000            70000

# Dealing with duplicated values

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [names, age, dept, salaries, promoted_salary]
Index: []

In [ ]:
df[df.duplicated(keep='first')]
df[df.duplicated(keep='last')]

Empty DataFrame
Columns: [names, age, dept, salaries, promoted_salary]
Index: []

# Using lambda in apply function

In [ ]:
df['promoted_salaries']=df['salaries'].apply(lambda x:x+10000 if x<45000 else x)
df

     names   age     dept  salaries  promoted_salary  promoted_salaries
0   mukesh  22.0       it     35000            45000              45000
1      sai  21.0       hr     40000            50000              50000
2  sathish  25.0  finance     45000            55000              45000
3    srinu  20.0       it     50000            60000              50000
4   ramesh   NaN       hr     55000            65000              55000
5    venky  35.0       hr     60000            70000              60000

# Merging two documents

In [ ]:
data2={
    'dept':['it','finance'],
    'location':['naresraopet','guntur'],
    'manager':['kushal','vinod']
}

In [ ]:
data2

{'dept': ['it', 'finance'],
 'location': ['naresraopet', 'guntur'],
 'manager': ['kushal', 'vinod']}

In [ ]:
df2=pd.DataFrame(data2)
df2

      dept     location manager
0       it  naresraopet  kushal
1  finance       guntur   vinod

In [ ]:
#using concat
pd.concat([df,df2])

,names,age,dept,salaries,promoted_salary,promoted_salaries,location,manager
0,mukesh,22.0,it,35000.0,45000.0,45000.0,NaN,NaN
1,sai,21.0,hr,40000.0,50000.0,50000.0,NaN,NaN
2,sathish,25.0,finance,45000.0,55000.0,45000.0,NaN,NaN
3,srinu,20.0,it,50000.0,60000.0,50000.0,NaN,NaN
4,ramesh,NaN,hr,55000.0,65000.0,55000.0,NaN,NaN
5,venky,35.0,hr,60000.0,70000.0,60000.0,NaN,NaN
0,NaN,NaN,it,NaN,NaN,NaN,naresraopet,kushal
1,NaN,NaN,finance,NaN,NaN,NaN,guntur,vinod

In [ ]:
#axis=1
pd.concat([df,df2],axis=1)

,names,age,dept,salaries,promoted_salary,promoted_salaries,dept,location,manager
0,mukesh,22.0,it,35000,45000,45000,it,naresraopet,kushal
1,sai,21.0,hr,40000,50000,50000,finance,guntur,vinod
2,sathish,25.0,finance,45000,55000,45000,NaN,NaN,NaN
3,srinu,20.0,it,50000,60000,50000,NaN,NaN,NaN
4,ramesh,NaN,hr,55000,65000,55000,NaN,NaN,NaN
5,venky,35.0,hr,60000,70000,60000,NaN,NaN,NaN

In [ ]:
pd.merge(df,df2,on='dept')

,names,age,dept,salaries,promoted_salary,promoted_salaries,location,manager
0,mukesh,22.0,it,35000,45000,45000,naresraopet,kushal
1,sathish,25.0,finance,45000,55000,45000,guntur,vinod
2,srinu,20.0,it,50000,60000,50000,naresraopet,kushal

# Importing a file

In [ ]:
# pd.read_csv("path")